apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: productpricing
spec:
  replicas: 3
  template:
    metadata:
      labels:
        service: productpricing
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: productpricing 
        image: riazvm/publicrepo:productpricingservice.1.0
        ports:
        - name: http
          containerPort: 8080
        - name: prometheus-jmx
          containerPort: 9099
        env:
          - name: JAEGER_SERVICE_NAME
            value: productpricingservice
          - name: JAEGER_AGENT_HOST
            value: jaeger-agent
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
          - name: JAEGER_REPORTER_LOG_SPANS
            value: "true"
          - name: JAEGER_TAGS
            value: "version=${VERSION}"
          - name: OPENTRACING_METRICS_EXPORTER_HTTP_PATH
            value: "/metrics"
---
kind: Service
apiVersion: v1
metadata:
  name: productpricing
  labels:
    service: productpricing
spec:
  type: LoadBalancer
  selector:
    service: productpricing
  ports:
  - name: http
    port: 8080