global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'orderservice'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.123:9091']
        labels:
          application: 'orderservice'
          