---
apiVersion: v1
kind: Service
metadata:
  name: mysqlproducts
  namespace: tracing
  labels:
    app: mysqlproducts
spec:
  ports:
  - port: 3306
    name: mysql
  clusterIP: None
  selector:
    app: mysqlproducts
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysqlproducts
  namespace: tracing
spec:
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql.root.password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-vol
          mountPath: /var/lib/mysql
        - name: mysql-config
          mountPath: /bin/products-install.sh
          subPath: products-install.sh
        - name: mysql-start
          mountPath: /bin/mysql-start.sh
          subPath: mysql-start.sh
        command: ["/bin/mysql-start.sh"]
      volumes:
      - name: mysql-vol
        persistentVolumeClaim:
          claimName: mysql-claim
      - name: mysql-config
        configMap:
          defaultMode: 0700
          name: mysql-config-map
      - name: mysql-start
        configMap:
          defaultMode: 0700
          name: mysql-start-map
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config-map
  namespace: tracing
data:
  products-install.sh: |
    #!/bin/sh
    # sleep while mysql is starting up
    while [ -z "$ALIVE" ] || [ "$ALIVE" != 'mysqld is alive' ]
    do
      echo "waiting for mysql..."
      sleep 3
      ALIVE=`mysqladmin ping --user=root --password=$MYSQL_ROOT_PASSWORD`
      echo "status: $ALIVE"
    done
    echo "MYSQL is alive, checking user..."
    USEREXIST=`mysql --user=root --password=$MYSQL_ROOT_PASSWORD -e 'select user from mysql.user;' | grep productmaster`
    if ! [ -z "$USEREXIST" ]
    then
      echo "productmaster user already installed."
    else
      echo "------- PRODUCTMASTER USER SETUP -------"
      echo "updating apt-get..."
      apt-get update
      echo "apt-get installing curl..."
      apt-get --assume-yes install curl
      apt-get --assume-yes install wget
      echo "downloading productmaster scripts..."
      mkdir ~/productmaster
      mkdir ~/productmaster/db-install
      cd ~/productmaster/db-install
      curl -L -o create-productmaster-db.sh https://github.com/yfauser/planespotter/raw/master/db-install/create-productmaster-db.sh
      curl -L -o create-productmaster-db.sql https://github.com/yfauser/planespotter/raw/master/db-install/create-productmaster-db.sql
      curl -L -o delete-productmaster-db.sh https://github.com/yfauser/planespotter/raw/master/db-install/delete-productmaster-db.sh
      curl -L -o delete-productmaster-db.sql https://github.com/yfauser/planespotter/raw/master/db-install/delete-productmaster-db.sql
      echo "creating a new productmaster db"
      chmod +x create-productmaster-db.sh
      ./create-productmaster-db.sh
    fi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-start-map
  namespace: tracing
data:
  mysql-start.sh: |
    #!/bin/sh
    echo "starting products-install in background"
    /bin/products-install.sh &
    echo "starting mysqld.."
    /entrypoint.sh mysqld