apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: product
  namespace: tracing
spec:
  replicas: 3
  template:
    metadata:
      labels:
        service: product
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: product 
        image: riazvm/publicrepo:productservice1.0
        ports:
        - name: http
          containerPort: 9090
        - name: prometheus-jmx
          containerPort: 9099
        env:
          - name: JAEGER_SERVICE_NAME
            value: productservice
          - name: JAEGER_AGENT_HOST
            value: jaeger-all-in-one-agent
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
          - name: JAEGER_REPORTER_LOG_SPANS
            value: "true"
          - name: JAEGER_TAGS
            value: "version=${VERSION}"
          - name: OPENTRACING_METRICS_EXPORTER_HTTP_PATH
            value: "/metrics"
          - name: PRICING_URL
            value: "http://productpricing:8080"
          - name: DB_PORT
            value: 3306
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql.username        
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql.root.password
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql.root.password 
          - name: DB_SERVICE
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: mysql.service.name   
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: mysql.db.name
kind: Service
apiVersion: v1
metadata:
  name: product
  namespace: tracing
  labels:
    service: product
spec:
  type: LoadBalancer
  selector:
    service: product
  ports:
  - name: http
    port: 9090