apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account
spec:
  replicas: 3
  template:
    metadata:
      labels:
        service: account
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: account 
        image: riazvm/publicrepo:accountservice6.0
        ports:
        - name: http
          containerPort: 8080
        - name: prometheus-jmx
          containerPort: 9099
        env:
          - name: JAEGER_SERVICE_NAME
            value: account
          - name: JAEGER_AGENT_HOST
            value: jaeger-all-in-one-agent
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
          - name: JAEGER_REPORTER_LOG_SPANS
            value: "true"
          - name: JAEGER_TAGS
            value: "version=${VERSION}"
          - name: OPENTRACING_METRICS_EXPORTER_HTTP_PATH
            value: "/metrics"
          - name: PRICING_URL
            value: "http://accounts:8080"
---
kind: Service
apiVersion: v1
metadata:
  name: account
  labels:
    service: account
spec:
  type: LoadBalancer
  selector:
    service: account
  ports:
  - name: http
    port: 8080